services:
  - type: web
    name: sp-evaluator-free
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: API_BASE
        value: https://speval.tokenengine.ai/api/funnel
